import './globals.css';
import { Poppins } from 'next/font/google';
import Header from './components/Header';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-BR'>
      <body className={`${poppins.className} max-w-[1280px] mx-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
